<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net10.0</TargetFrameworks>
        <Configurations>Debug;Release-4-12-0;Release-4-14-0;Release-5-0-0;Release-5-3-0;Release</Configurations>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <Platforms>x64</Platforms>

        <RootNamespace>RoslynHelpers</RootNamespace>
		<Version>3.0.2</Version>
		<Authors>David Le Bansais</Authors>
		<Company />
		<Product />
		<Description>A set of helpers to assist Roslyn analyzers</Description>
        <Copyright>Copyright © 2026 David Le Bansais</Copyright>
        <AssemblyVersion>3.0.2.28</AssemblyVersion>
		<FileVersion>3.0.2.28</FileVersion>
		<RepositoryUrl>https://github.com/dlebansais/RoslynHelpers</RepositoryUrl>
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>

        <NeutralLanguage>en-US</NeutralLanguage>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>

        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageLicenseExpression>0BSD</PackageLicenseExpression>
        <PackageIcon>package-icon.png</PackageIcon>
        <PackageReadmeFile>README-short.md</PackageReadmeFile>
    </PropertyGroup>

	<PropertyGroup Condition="'$(APPVEYOR)' == 'True'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

    <PropertyGroup Condition="'$(APPVEYOR_PULL_REQUEST_NUMBER)' == ''">
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>..\signing.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
		<None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
        <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.IDisposableAnalyzers" Version="4.0.8.17">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="PolySharp" Version="1.16.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.Method.Contracts.Analyzers-Debug" Version="3.0.6" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.Method.Contracts.Analyzers" Version="3.0.6" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- Use 5.0.0 for Debug until AppVeyor is updated to 5.3.0 -->
        <!-- Default to 4.12.0 for Release for maximum compatibility -->
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" Condition="'$(Configuration)' == 'Release-4-12-0' Or '$(Configuration)' == 'Release'" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" Condition="'$(Configuration)' == 'Release-4-14-0'" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" Condition="'$(Configuration)' == 'Release-5-0-0' Or '$(Configuration)' == 'Debug'" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" Condition="'$(Configuration)' != 'Release-4-12-0' And '$(Configuration)' != 'Release-4-14-0' And '$(Configuration)' != 'Release-5-0-0' And '$(Configuration)' != 'Debug' And '$(Configuration)' != 'Release'" />

        <PackageReference Include="dlebansais.Method.Contracts-Debug" Version="3.0.0" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
        <PackageReference Include="dlebansais.Method.Contracts" Version="3.0.0" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'" />
    </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SolutionDir)'!='*Undefined*'">
		<Exec Command="if exist &quot;$(SolutionDir)updatecommit.bat&quot; call &quot;$(SolutionDir)updatecommit.bat&quot; &quot;$(SolutionDir)&quot; &quot;$(TargetPath)&quot;" />
		<Exec Command="if exist &quot;$(SolutionDir)signfile.bat&quot; call &quot;$(SolutionDir)signfile.bat&quot; &quot;$(SolutionDir)&quot; &quot;$(Configuration)-$(Platform)&quot; &quot;$(TargetPath)&quot;" Condition="'$(Configuration)'=='Release'" />

        <ItemGroup>
            <None Remove="@(None)" />
        </ItemGroup>

        <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
            <None Include="$(TargetDir)$(ProjectName).dll" />
            <None Include="$(TargetDir)$(ProjectName).pdb" />
            <None Include="$(TargetDir)$(ProjectName).xml" />
        </ItemGroup>
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget-debug\lib\$(TargetFramework)\" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
        <Copy SourceFiles="package-icon.png" DestinationFolder="$(SolutionDir)nuget-debug\" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
        <Copy SourceFiles="README-short.md" DestinationFolder="$(SolutionDir)nuget-debug\" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />

        <ItemGroup Condition="'$(Configuration)|$(Platform)'!='Debug|x64'">
            <None Include="$(TargetDir)$(ProjectName).dll" />
            <None Include="$(TargetDir)$(ProjectName).xml" />
        </ItemGroup>
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget\lib\$(TargetFramework)\roslyn4.12\" Condition="'$(Configuration)|$(Platform)' == 'Release-4-12-0|x64'" />
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget\lib\$(TargetFramework)\roslyn4.14\" Condition="'$(Configuration)|$(Platform)' == 'Release-4-14-0|x64'" />
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget\lib\$(TargetFramework)\roslyn5.0\" Condition="'$(Configuration)|$(Platform)' == 'Release-5-0-0|x64'" />
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget\lib\$(TargetFramework)\roslyn5.3\" Condition="'$(Configuration)|$(Platform)' == 'Release-5-3-0|x64'" />
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget\lib\$(TargetFramework)\" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'" />
        <Copy SourceFiles="package-icon.png" DestinationFolder="$(SolutionDir)nuget\" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'" />
        <Copy SourceFiles="README-short.md" DestinationFolder="$(SolutionDir)nuget\" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'" />
    </Target>

</Project>
